static const Rule rules[]       = {
	/* xprop(1):
	 *	WM_CLASS(STRING) = instance, class
	 *	WM_NAME(STRING) = title
	 */
	/* class                   instance         title                 tags mask     isfloating    isterminal  noswallow   monitor scratchpad */
	{ CLASS_SP,                NULL,            TITLE_SP,             0,            1,            0,          0,          -1,     't' },
	{ CLASS_SP,                NULL,            "spotify",            0,            1,            0,          0,          -1,     's' },
	{ CLASS_SP,                NULL,            "calendar",           0,            1,            0,          0,          -1,     'c' },
	{ "Qalculate-gtk",         NULL,            NULL,                 0,            1,            0,          0,          -1,     'c' },
	{ "qalculate-qt",          NULL,            NULL,                 0,            1,            0,          0,          -1,     'c' },
	{ "org.gnome.Characters",  NULL,            NULL,                 0,            1,            0,          0,          -1,     'c' },
	{ "firefox",               "Toolkit",       "Picture-in-Picture", 0,            1,            0,          0,          -1,     'c' },
	{ "librewolf",             "Toolkit",       "Picture-in-Picture", 0,            1,            0,          0,          -1,     'c' },
	{ "Gtk3-icon-browser",     NULL,            NULL,                 0,            1,            0,          0,          -1,     'c' },
	{ "Eww",                   "eww",           "eww",                0,            1,            0,          0,          -1,     'c' },
	{ "eww-pwcalc",            NULL,            NULL,                 0,            1,            0,          0,          -1,     'c' },
	{ "explorer.exe",          NULL,            "Wine System Tray",   0,            1,            0,          0,          -1,     'c' },
	{ "Pwcalculator",          NULL,            NULL,                 0,            1,            0,          0,          -1,     0 },
	{ "Blueberry.py",          NULL,            NULL,                 0,            1,            0,          0,          -1,     0 },
	{ "Pavucontrol",           NULL,            NULL,                 0,            1,            0,          0,          -1,     0 },
	{ "Arandr",                NULL,            NULL,                 0,            1,            0,          0,          -1,     0 },
	{ NULL,                    NULL,            "Event Tester",       0,            1,            0,          1,          -1,     0 },	
	{ "Rofi",                  NULL,            NULL,                 0,            1,            0,          0,          -1,     0 },
	{ "st-256color",           NULL,            NULL,                 1,            0,            1,          0,          -1,     0 },
	{ "Alacritty",             NULL,            NULL,                 1,            0,            1,          0,          -1,     0 },
	{ "tabbed",                "terminal",      NULL,                 1,            0,            1,          0,          -1,     0 },
	{ "Kgx",                   NULL,            NULL,                 1,            0,            1,          0,          -1,     0 },
	{ "firefox",               "Navigator",     NULL,                 1 << 1,       0,            0,          0,          -1,     0 },
	{ "librewolf",             "Navigator",     NULL,                 1 << 1,       0,            0,          0,          -1,     0 },
	{ NULL,                    "Places",        NULL,                 1 << 1,       1,            0,          0,          -1,     0 },
	{ "Gedit",                 NULL,            NULL,                 1 << 2,       0,            0,          0,          -1,     0 },
	{ "Emacs",                 NULL,            NULL,                 1 << 2,       0,            0,          0,          -1,     0 },
	{ "nvim-qt",               NULL,            NULL,                 1 << 2,       0,            0,          0,          -1,     0 },
	{ NULL,                    "libreoffice",   NULL,                 1 << 2,       0,            0,          0,          -1,     0 },
	{ "Gimp",                  NULL,            NULL,                 1 << 2,       0,            0,          0,          -1,     0 },
	{ "Evince",                NULL,            NULL,                 1 << 2,       0,            0,          0,          -1,     0 },
	{ "calibre",               NULL,            NULL,                 1 << 2,       0,            0,          0,          -1,     0 },
	{ "org.gnome.Nautilus",    NULL,            NULL,                 1 << 3,       0,            0,          0,          -1,     0 },
	{ "bottles",               NULL,            NULL,                 1 << 3,       0,            0,          0,          -1,     0 },
	{ "Geary",                 NULL,            NULL,                 1 << 4,       0,            0,          0,          -1,     0 },
	{ "discord",               NULL,            NULL,                 1 << 4,       0,            0,          0,          -1,     0 },
	{ "spot",                  NULL,            NULL,                 1 << 4,       0,            0,          0,          -1,     0 },
	{ "Lutris",                NULL,            NULL,                 1 << 5,       0,            0,          0,          -1,     0 },
	{ NULL,                    NULL,            "Steam",              1 << 5,       0,            0,          0,          -1,     0 },
	{ "Steam",                 NULL,            "Steam",              1 << 5,       0,            0,          0,          -1,     0 },
	{ "Steam",                 NULL,            "Lista de amigos",    1 << 5,       1,            0,          0,          -1,     0 },
	{ "Steam",                 NULL,            "Steam  Novidades",   1 << 5,       1,            0,          0,          -1,     0 },
	{ "Rare",                  NULL,            NULL,                 1 << 5,       0,            0,          0,          -1,     0 },
	{ "PrismLauncher",         NULL,            NULL,                 1 << 5,       1,            0,          0,          -1,     0 },
	{ "gamescope",             NULL,            NULL,                 1 << 5,       1,            0,          0,          -1,     0 },
	{ "steam_proton",          NULL,            NULL,                 1 << 5,       0,            0,          0,          -1,     0 },
	{ "epicgameslauncher.exe", NULL,            NULL,                 1 << 5,       0,            0,          0,          -1,     0 },
	{ "ProtonUp-Qt",           NULL,            NULL,                 1 << 5,       1,            0,          0,          -1,     0 },
	{ NULL,                    NULL,            "Protontricks",       1 << 5,       1,            0,          0,          -1,     0 },
	// { "stalonetray",           NULL,            NULL,                 0,            1,            0,          1,          -1,     'a' },
};
